/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ibakimchivljvnydqxog"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliYWtpbWNoaXZsanZueWRxeG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MzQwNTAsImV4cCI6MjA3NjIxMDA1MH0.62QdH6GLHPTtRQ-lO-myZTq3PNmHkFoyLy6Q065i9ho"